### ISSUE TITLE
Error: "TypeError: Cannot read property 'reference' of undefined"

### ISSUE THREAD

**Issue by Bnaya** [eps1lon/yarn-plugin-deduplicate#7]
I'm getting:
"TypeError: Cannot read property 'reference' of undefined" when running yarn deduplicate
```
gitpod /workspace/objectbuffer $ yarn deduplicate
➤ YN0000: ┌ deduplication step
➤ YN0001: │ TypeError: Cannot read property 'reference' of undefined
    at Module.B (/workspace/objectbuffer/.yarn/releases/yarn-2.1.1.cjs:2:345743)
    at /workspace/objectbuffer/.yarn/plugins/@yarnpkg/plugin-deduplicate.cjs:200:73
    at Array.map (<anonymous>)
    at deduplicate (/workspace/objectbuffer/.yarn/plugins/@yarnpkg/plugin-deduplicate.cjs:197:54)
    at /workspace/objectbuffer/.yarn/plugins/@yarnpkg/plugin-deduplicate.cjs:146:11
    at f.startTimerSync (/workspace/objectbuffer/.yarn/releases/yarn-2.1.1.cjs:2:313391)
    at /workspace/objectbuffer/.yarn/plugins/@yarnpkg/plugin-deduplicate.cjs:145:16
    at Function.start (/workspace/objectbuffer/.yarn/releases/yarn-2.1.1.cjs:2:312958)
    at DeduplicateCommand.execute (/workspace/objectbuffer/.yarn/plugins/@yarnpkg/plugin-deduplicate.cjs:140:98)
    at async DeduplicateCommand.validateAndExecute (/workspace/objectbuffer/.yarn/releases/yarn-2.1.1.cjs:2:551219)
➤ YN0000: └ Completed
```
repro:
Open the following project in gitpod
https://gitpod.io/#https://github.com/Bnaya/objectbuffer
run `yarn deduplicate` in the terminal

**Comment by eps1lon** [comment]
Could you check if this still reproduces with the canary?

`yarn plugin import https://raw.githubusercontent.com/eps1lon/yarn-plugin-deduplicate/latest/bundles/%40yarnpkg/plugin-deduplicate.js`?

I think I just need to cut a release.

**Comment by Bnaya** [comment]
Works on maser, thanks!
That's the result:
https://github.com/Bnaya/objectbuffer/pull/127

Do you think you will add support for `strategy` and `--fail` flags?
Thanks again!

**Comment by eps1lon** [comment]
> Do you think you will add support for strategy and --fail flags?

I don't think I'll be needing those so someone else would have to work on it.

Just cut a new release and `yarn plugin import https://raw.githubusercontent.com/eps1lon/yarn-plugin-deduplicate/latest/bin/%40yarnpkg/plugin-deduplicate.js` as recommended in the README should work again.
